name: Python CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        # Step 1: Checkout Code
        - name: Checkout code
          uses: actions/checkout@v2

        # Step 2: Set up Python
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
              python-version: '3.x'

        # Step 3: Install dependencies
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

        # Step 4: Download ChromeDriver
        - name: Install Chrome and ChromeDriver
          run: |
              sudo apt-get update
              sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
              
              # Install or update Google Chrome (ignore errors if it's already installed)
              sudo apt-get install -y google-chrome-stable || true

              # Get latest ChromeDriver version
              CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+.[0-9]+.[0-9]+')
              DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || echo "0")

              if [ "$DRIVER_VERSION" != "0" ]; then
                  # Download ChromeDriver
                  wget -N https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
                  unzip -o chromedriver_linux64.zip -d driver/
                  chmod +x driver/chromedriver
              else
                  echo "Failed to fetch ChromeDriver version. Ensure Chrome version is supported."
                  exit 1
              fi

        # Step 5: Run Python script
        - name: Run script
          run: |
              python main.py
