name: Python CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        # Step 1: Checkout Code
        - name: Checkout code
          uses: actions/checkout@v2

        # Step 2: Set up Python
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
              python-version: '3.x'

        # Step 3: Install dependencies
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

        # Step 4: Download ChromeDriver
        - name: Install Chrome and ChromeDriver
          run: | 
                sudo apt-get update
                sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4

                # Install Google Chrome
                sudo apt-get install -y google-chrome-stable || true

                # Determine installed Chrome version
                CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
                if [ -z "$CHROME_VERSION" ]; then
                    echo "Google Chrome installation failed or not found."
                    exit 1
                fi
                echo "Installed Chrome version: $CHROME_VERSION"

                # Fetch compatible ChromeDriver version
                DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}")
                if [ -z "$DRIVER_VERSION" ]; then
                    echo "Failed to fetch ChromeDriver version for Chrome $CHROME_VERSION. Falling back to latest ChromeDriver."
                    DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
                fi

                if [ -n "$DRIVER_VERSION" ]; then
                    echo "Using ChromeDriver version: $DRIVER_VERSION"
                    wget -N https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
                    unzip -o chromedriver_linux64.zip -d driver/
                    chmod +x driver/chromedriver
                else
                    echo "Unable to fetch any ChromeDriver version. Exiting."
                    exit 1
                fi

                # Verify ChromeDriver installation
                ./driver/chromedriver --version


        # Step 5: Run Python script
        - name: Run script
          run: |
              python main.py
